apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kv-store
  template:
    metadata:
      labels:
        app: kv-store
    spec:
      containers:
      - name: kv-store
        image: kvacrgsp.azurecr.io/kv_store:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret

